[project]
name = "ekf-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "pyquaternion>=0.9.9",
    "scipy>=1.16.0",
    "sympy>=1.14.0",
]
