################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.c \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.c \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.c \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.c \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.c \
../Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.c \
../Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.c \
../Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.c \
../Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.c \
../Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.c \
../Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.c \
../Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.c \
../Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.c \
../Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.c \
../Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.c \
../Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.c \
../Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.c \
../Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.c \
../Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.c \
../Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.c \
../Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.c \
../Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.c \
../Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.c \
../Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.c \
../Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.c \
../Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.c \
../Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.c \
../Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.c \
../Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.c \
../Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.c \
../Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.c \
../Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.c \
../Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.c \
../Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.c \
../Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.c \
../Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.c \
../Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.c \
../Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.c \
../Core/Inc/dsdlc_generated/src/mppt.Stream.c \
../Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.c \
../Core/Inc/dsdlc_generated/src/uavcan.Timestamp.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.c \
../Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.c \
../Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.c \
../Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.c 

C_DEPS += \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.d \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.d \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.d \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.d \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.d \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.d \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.d \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.d \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.d \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.d \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.d \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.d \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.d \
./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.d \
./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.d \
./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.d \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.d \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.d \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.d \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.d \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.d \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.d \
./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.d \
./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.d \
./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.d \
./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.d \
./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.d \
./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.d \
./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.d \
./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.d \
./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.d \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.d \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.d \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.d \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.d \
./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.d \
./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.d \
./Core/Inc/dsdlc_generated/src/mppt.Stream.d \
./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.d \
./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.d \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.d \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.d \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.d 

OBJS += \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.o \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.o \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.o \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.o \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.o \
./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.o \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.o \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.o \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.o \
./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.o \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.o \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.o \
./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.o \
./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.o \
./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.o \
./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.o \
./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.o \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.o \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.o \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.o \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.o \
./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.o \
./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.o \
./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.o \
./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.o \
./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.o \
./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.o \
./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.o \
./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.o \
./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.o \
./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.o \
./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.o \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.o \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.o \
./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.o \
./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.o \
./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.o \
./Core/Inc/dsdlc_generated/src/mppt.Stream.o \
./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.o \
./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.o \
./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.o \
./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.o \
./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.o 


# Each subdirectory must supply rules for building sources it contributes
Core/Inc/dsdlc_generated/src/%.o Core/Inc/dsdlc_generated/src/%.su Core/Inc/dsdlc_generated/src/%.cyclo: ../Core/Inc/dsdlc_generated/src/%.c Core/Inc/dsdlc_generated/src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DDEBUG -DUSE_NUCLEO_64 -DUSE_HAL_DRIVER -DSTM32L552xx -c -I../Core/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../Drivers/BSP/STM32L5xx_Nucleo -I../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-Inc-2f-dsdlc_generated-2f-src

clean-Core-2f-Inc-2f-dsdlc_generated-2f-src:
	-$(RM) ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryCells.su ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryContinuous.su ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryInfoAux.su ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.power.BatteryPeriodic.su ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.proximity_sensor.Proximity.su ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.d ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.o ./Core/Inc/dsdlc_generated/src/ardupilot.equipment.trafficmonitor.TrafficReport.su ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.d ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.o ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Heading.su ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.d ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.o ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.MovingBaselineData.su ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.d ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.o ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.RelPosHeading.su ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.d ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.o ./Core/Inc/dsdlc_generated/src/ardupilot.gnss.Status.su ./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.d ./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.o ./Core/Inc/dsdlc_generated/src/ardupilot.indication.Button.su ./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.d ./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.o ./Core/Inc/dsdlc_generated/src/ardupilot.indication.NotifyState.su ./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.cyclo ./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.d ./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.o ./Core/Inc/dsdlc_generated/src/ardupilot.indication.SafetyState.su ./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.cyclo ./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.d ./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.o ./Core/Inc/dsdlc_generated/src/com.hex.equipment.flow.Measurement.su ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.cyclo ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.d ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.o ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoCmd.su ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.cyclo ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.d ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.o ./Core/Inc/dsdlc_generated/src/com.himark.servo.ServoInfo.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetEscID.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMaintenanceInformation_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.GetMajorConfig_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.cyclo
	-$(RM) ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.RawCommand.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SelfTest_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetAngle_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetBaud_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetDirection_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetID_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetLED_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetReportingFrequency_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_req.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.SetThrottleSource_res.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg1.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg2.su ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.cyclo ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.d ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.o ./Core/Inc/dsdlc_generated/src/com.hobbywing.esc.StatusMsg3.su ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.cyclo ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.d ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.o ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.FocCtrl.su ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.cyclo ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.d ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.o ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHCAN.su ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.cyclo ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.d ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.o ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.PUSHSCI.su
	-$(RM) ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.cyclo ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.d ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.o ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamCfg.su ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.cyclo ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.d ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.o ./Core/Inc/dsdlc_generated/src/com.tmotor.esc.ParamGet.su ./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.cyclo ./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.d ./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.o ./Core/Inc/dsdlc_generated/src/com.volz.servo.ActuatorStatus.su ./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.cyclo ./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.d ./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.o ./Core/Inc/dsdlc_generated/src/com.xacti.CopterAttStatus.su ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.cyclo ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.d ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.o ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalAttitudeStatus.su ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.cyclo ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.d ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.o ./Core/Inc/dsdlc_generated/src/com.xacti.GimbalControlData.su ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.cyclo ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.d ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.o ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatus.su ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.cyclo ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.d ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.o ./Core/Inc/dsdlc_generated/src/com.xacti.GnssStatusReq.su ./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.cyclo ./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.d ./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.o ./Core/Inc/dsdlc_generated/src/cuav.equipment.power.CBAT.su ./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.d ./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.o ./Core/Inc/dsdlc_generated/src/dronecan.protocol.CanStats.su ./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.d ./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.o ./Core/Inc/dsdlc_generated/src/dronecan.protocol.Stats.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.ArmStatus.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.BasicID.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.Location.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.OperatorID.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_req.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SecureCommand_res.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.SelfID.su ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.d ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.o ./Core/Inc/dsdlc_generated/src/dronecan.remoteid.System.su ./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.d ./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.o ./Core/Inc/dsdlc_generated/src/dronecan.sensors.hygrometer.Hygrometer.su ./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d ./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o ./Core/Inc/dsdlc_generated/src/dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.su ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.d ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.o ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rc.RCInput.su ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.cyclo ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.d ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.o ./Core/Inc/dsdlc_generated/src/dronecan.sensors.rpm.RPM.su ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.cyclo ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.d ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.o
	-$(RM) ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_req.su ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.cyclo ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.d ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.o ./Core/Inc/dsdlc_generated/src/mppt.OutputEnable_res.su ./Core/Inc/dsdlc_generated/src/mppt.Stream.cyclo ./Core/Inc/dsdlc_generated/src/mppt.Stream.d ./Core/Inc/dsdlc_generated/src/mppt.Stream.o ./Core/Inc/dsdlc_generated/src/mppt.Stream.su ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.d ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.o ./Core/Inc/dsdlc_generated/src/uavcan.CoarseOrientation.su ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.d ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.o ./Core/Inc/dsdlc_generated/src/uavcan.Timestamp.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.ArrayCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Command.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.actuator.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.MagneticFieldStrength2.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.RawIMU.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ahrs.Solution.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.AngleOfAttack.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.IndicatedAirspeed.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.RawAirData.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.Sideslip.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticPressure.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.StaticTemperature.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.air_data.TrueAirspeed.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.device.Temperature.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RPMCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.RawCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.o
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.esc.StatusExtended.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Auxiliary.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.ECEFPositionVelocity.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.Fix2.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.gnss.RTCMStream.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Command.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.hardpoint.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.FuelTankStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.CylinderStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.ice.reciprocating.Status.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.BeepCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.LightsCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.RGB565.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.indication.SingleLightCommand.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.BatteryInfo.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.CircuitStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.power.PrimaryPowerSupplyStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.range_sensor.Measurement.su ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.equipment.safety.ArmingStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.d
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.o ./Core/Inc/dsdlc_generated/src/uavcan.navigation.GlobalNavigationSolution.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.AccessCommandShell_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.CANIfaceStats.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.DataTypeKind.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetDataTypeInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetNodeInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GetTransportStats_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.GlobalTimeSync.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.HardwareVersion.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.NodeStatus.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.Panic.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.RestartNode_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.SoftwareVersion.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.KeyValue.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogLevel.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.debug.LogMessage.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.Allocation.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.d
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.AppendEntries_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Discovery.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.Entry.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.dynamic_node_id.server.RequestVote_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Begin_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.enumeration.Indication.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.BeginFirmwareUpdate_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Delete_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.EntryType.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Error.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetDirectoryEntryInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.GetInfo_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Path.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.cyclo
	-$(RM) ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Read_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.file.Write_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Empty.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.ExecuteOpcode_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_req.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.GetSet_res.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.NumericValue.su ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.d ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.o ./Core/Inc/dsdlc_generated/src/uavcan.protocol.param.Value.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Broadcast.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_req.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Call_res.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Protocol.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.SerialConfig.su ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.cyclo ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.d ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.o ./Core/Inc/dsdlc_generated/src/uavcan.tunnel.Targetted.su

.PHONY: clean-Core-2f-Inc-2f-dsdlc_generated-2f-src

