################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.cpp \
../Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.cpp \
../Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.cpp \
../Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.cpp \
../Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.cpp \
../Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.cpp \
../Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.cpp \
../Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.cpp \
../Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.cpp \
../Core/dsdlc_generated/test/test_ardupilot.gnss.Status.cpp \
../Core/dsdlc_generated/test/test_ardupilot.indication.Button.cpp \
../Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.cpp \
../Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.cpp \
../Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.cpp \
../Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.cpp \
../Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.cpp \
../Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.cpp \
../Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.cpp \
../Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.cpp \
../Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.cpp \
../Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.cpp \
../Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.cpp \
../Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.cpp \
../Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.cpp \
../Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.cpp \
../Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.cpp \
../Core/dsdlc_generated/test/test_com.xacti.GnssStatus.cpp \
../Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.cpp \
../Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.cpp \
../Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.cpp \
../Core/dsdlc_generated/test/test_dronecan.protocol.Stats.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.Location.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.cpp \
../Core/dsdlc_generated/test/test_dronecan.remoteid.System.cpp \
../Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.cpp \
../Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.cpp \
../Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.cpp \
../Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.cpp \
../Core/dsdlc_generated/test/test_mppt.OutputEnable_request.cpp \
../Core/dsdlc_generated/test/test_mppt.OutputEnable_response.cpp \
../Core/dsdlc_generated/test/test_mppt.Stream.cpp \
../Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.cpp \
../Core/dsdlc_generated/test/test_uavcan.Timestamp.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.cpp \
../Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.Panic.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.cpp \
../Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.cpp \
../Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.cpp 

OBJS += \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.o \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.o \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.o \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.o \
./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.o \
./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.o \
./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.o \
./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.o \
./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.o \
./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.o \
./Core/dsdlc_generated/test/test_ardupilot.indication.Button.o \
./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.o \
./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.o \
./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.o \
./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.o \
./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.o \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.o \
./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.o \
./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.o \
./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.o \
./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.o \
./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.o \
./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.o \
./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.o \
./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.o \
./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.o \
./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.o \
./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.o \
./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.o \
./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.o \
./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.o \
./Core/dsdlc_generated/test/test_dronecan.remoteid.System.o \
./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.o \
./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o \
./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.o \
./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.o \
./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.o \
./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.o \
./Core/dsdlc_generated/test/test_mppt.Stream.o \
./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.o \
./Core/dsdlc_generated/test/test_uavcan.Timestamp.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.o \
./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.o \
./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.o \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.o \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.o 

CPP_DEPS += \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.d \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.d \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.d \
./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.d \
./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.d \
./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.d \
./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.d \
./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.d \
./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.d \
./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.d \
./Core/dsdlc_generated/test/test_ardupilot.indication.Button.d \
./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.d \
./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.d \
./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.d \
./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.d \
./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.d \
./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.d \
./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.d \
./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.d \
./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.d \
./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.d \
./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.d \
./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.d \
./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.d \
./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.d \
./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.d \
./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.d \
./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.d \
./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.d \
./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.d \
./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.d \
./Core/dsdlc_generated/test/test_dronecan.remoteid.System.d \
./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.d \
./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d \
./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.d \
./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.d \
./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.d \
./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.d \
./Core/dsdlc_generated/test/test_mppt.Stream.d \
./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.d \
./Core/dsdlc_generated/test/test_uavcan.Timestamp.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.d \
./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.d \
./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.d \
./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.d \
./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.d 


# Each subdirectory must supply rules for building sources it contributes
Core/dsdlc_generated/test/%.o Core/dsdlc_generated/test/%.su Core/dsdlc_generated/test/%.cyclo: ../Core/dsdlc_generated/test/%.cpp Core/dsdlc_generated/test/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m33 -std=gnu++14 -g3 -DDEBUG -DUSE_NUCLEO_64 -DUSE_HAL_DRIVER -DSTM32L552xx -c -I../Core/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc -I../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../Drivers/BSP/STM32L5xx_Nucleo -I../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-dsdlc_generated-2f-test

clean-Core-2f-dsdlc_generated-2f-test:
	-$(RM) ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryCells.su ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryContinuous.su ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryInfoAux.su ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.power.BatteryPeriodic.su ./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.proximity_sensor.Proximity.su ./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.cyclo ./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.d ./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.o ./Core/dsdlc_generated/test/test_ardupilot.equipment.trafficmonitor.TrafficReport.su ./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.cyclo ./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.d ./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.o ./Core/dsdlc_generated/test/test_ardupilot.gnss.Heading.su ./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.cyclo ./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.d ./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.o ./Core/dsdlc_generated/test/test_ardupilot.gnss.MovingBaselineData.su ./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.cyclo ./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.d ./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.o ./Core/dsdlc_generated/test/test_ardupilot.gnss.RelPosHeading.su ./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.cyclo ./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.d ./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.o ./Core/dsdlc_generated/test/test_ardupilot.gnss.Status.su ./Core/dsdlc_generated/test/test_ardupilot.indication.Button.cyclo ./Core/dsdlc_generated/test/test_ardupilot.indication.Button.d ./Core/dsdlc_generated/test/test_ardupilot.indication.Button.o ./Core/dsdlc_generated/test/test_ardupilot.indication.Button.su ./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.cyclo ./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.d ./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.o ./Core/dsdlc_generated/test/test_ardupilot.indication.NotifyState.su ./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.cyclo ./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.d ./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.o ./Core/dsdlc_generated/test/test_ardupilot.indication.SafetyState.su ./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.cyclo ./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.d ./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.o ./Core/dsdlc_generated/test/test_com.hex.equipment.flow.Measurement.su ./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.cyclo ./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.d ./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.o ./Core/dsdlc_generated/test/test_com.himark.servo.ServoCmd.su ./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.cyclo ./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.d ./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.o ./Core/dsdlc_generated/test/test_com.himark.servo.ServoInfo.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetEscID.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMaintenanceInformation_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.d
	-$(RM) ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.GetMajorConfig_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.RawCommand.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SelfTest_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetAngle_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetBaud_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetDirection_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetID_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetLED_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetReportingFrequency_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_request.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.SetThrottleSource_response.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg1.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg2.su ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.cyclo ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.d ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.o ./Core/dsdlc_generated/test/test_com.hobbywing.esc.StatusMsg3.su
	-$(RM) ./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.cyclo ./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.d ./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.o ./Core/dsdlc_generated/test/test_com.tmotor.esc.FocCtrl.su ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.cyclo ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.d ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.o ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHCAN.su ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.cyclo ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.d ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.o ./Core/dsdlc_generated/test/test_com.tmotor.esc.PUSHSCI.su ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.cyclo ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.d ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.o ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamCfg.su ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.cyclo ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.d ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.o ./Core/dsdlc_generated/test/test_com.tmotor.esc.ParamGet.su ./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.cyclo ./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.d ./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.o ./Core/dsdlc_generated/test/test_com.volz.servo.ActuatorStatus.su ./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.cyclo ./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.d ./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.o ./Core/dsdlc_generated/test/test_com.xacti.CopterAttStatus.su ./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.cyclo ./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.d ./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.o ./Core/dsdlc_generated/test/test_com.xacti.GimbalAttitudeStatus.su ./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.cyclo ./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.d ./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.o ./Core/dsdlc_generated/test/test_com.xacti.GimbalControlData.su ./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.cyclo ./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.d ./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.o ./Core/dsdlc_generated/test/test_com.xacti.GnssStatus.su ./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.cyclo ./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.d ./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.o ./Core/dsdlc_generated/test/test_com.xacti.GnssStatusReq.su ./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.cyclo ./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.d ./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.o ./Core/dsdlc_generated/test/test_cuav.equipment.power.CBAT.su ./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.cyclo ./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.d ./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.o ./Core/dsdlc_generated/test/test_dronecan.protocol.CanStats.su ./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.cyclo ./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.d ./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.o ./Core/dsdlc_generated/test/test_dronecan.protocol.Stats.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.ArmStatus.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.BasicID.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.Location.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.OperatorID.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_request.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.SecureCommand_response.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.SelfID.su ./Core/dsdlc_generated/test/test_dronecan.remoteid.System.cyclo ./Core/dsdlc_generated/test/test_dronecan.remoteid.System.d ./Core/dsdlc_generated/test/test_dronecan.remoteid.System.o ./Core/dsdlc_generated/test/test_dronecan.remoteid.System.su ./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.cyclo ./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.d ./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.o ./Core/dsdlc_generated/test/test_dronecan.sensors.hygrometer.Hygrometer.su ./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.cyclo
	-$(RM) ./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.d ./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.o ./Core/dsdlc_generated/test/test_dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.su ./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.cyclo ./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.d ./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.o ./Core/dsdlc_generated/test/test_dronecan.sensors.rc.RCInput.su ./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.cyclo ./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.d ./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.o ./Core/dsdlc_generated/test/test_dronecan.sensors.rpm.RPM.su ./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.cyclo ./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.d ./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.o ./Core/dsdlc_generated/test/test_mppt.OutputEnable_request.su ./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.cyclo ./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.d ./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.o ./Core/dsdlc_generated/test/test_mppt.OutputEnable_response.su ./Core/dsdlc_generated/test/test_mppt.Stream.cyclo ./Core/dsdlc_generated/test/test_mppt.Stream.d ./Core/dsdlc_generated/test/test_mppt.Stream.o ./Core/dsdlc_generated/test/test_mppt.Stream.su ./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.cyclo ./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.d ./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.o ./Core/dsdlc_generated/test/test_uavcan.CoarseOrientation.su ./Core/dsdlc_generated/test/test_uavcan.Timestamp.cyclo ./Core/dsdlc_generated/test/test_uavcan.Timestamp.d ./Core/dsdlc_generated/test/test_uavcan.Timestamp.o ./Core/dsdlc_generated/test/test_uavcan.Timestamp.su ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.ArrayCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.d ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.o ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Command.su ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.d ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.o ./Core/dsdlc_generated/test/test_uavcan.equipment.actuator.Status.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.MagneticFieldStrength2.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.RawIMU.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ahrs.Solution.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.AngleOfAttack.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.IndicatedAirspeed.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.RawAirData.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.Sideslip.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticPressure.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.d ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.StaticTemperature.su ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.d
	-$(RM) ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.o ./Core/dsdlc_generated/test/test_uavcan.equipment.air_data.TrueAirspeed.su ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.AngularCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.GEOPOICommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.d ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.o ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Mode.su ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.d ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.o ./Core/dsdlc_generated/test/test_uavcan.equipment.camera_gimbal.Status.su ./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.d ./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.o ./Core/dsdlc_generated/test/test_uavcan.equipment.device.Temperature.su ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RPMCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.RawCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.d ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.o ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.Status.su ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.d ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.o ./Core/dsdlc_generated/test/test_uavcan.equipment.esc.StatusExtended.su ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.d ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.o ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Auxiliary.su ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.d ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.o ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.ECEFPositionVelocity.su ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.d ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.o ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix.su ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.d ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.o ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.Fix2.su ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.d ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.o ./Core/dsdlc_generated/test/test_uavcan.equipment.gnss.RTCMStream.su ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.d ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.o ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Command.su ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.d ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.o ./Core/dsdlc_generated/test/test_uavcan.equipment.hardpoint.Status.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.FuelTankStatus.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.CylinderStatus.su ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.d ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.o ./Core/dsdlc_generated/test/test_uavcan.equipment.ice.reciprocating.Status.su ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.BeepCommand.su
	-$(RM) ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.LightsCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.d ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.o ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.RGB565.su ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.d ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.o ./Core/dsdlc_generated/test/test_uavcan.equipment.indication.SingleLightCommand.su ./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.d ./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.o ./Core/dsdlc_generated/test/test_uavcan.equipment.power.BatteryInfo.su ./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.d ./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.o ./Core/dsdlc_generated/test/test_uavcan.equipment.power.CircuitStatus.su ./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.d ./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.o ./Core/dsdlc_generated/test/test_uavcan.equipment.power.PrimaryPowerSupplyStatus.su ./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.d ./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.o ./Core/dsdlc_generated/test/test_uavcan.equipment.range_sensor.Measurement.su ./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.d ./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.o ./Core/dsdlc_generated/test/test_uavcan.equipment.safety.ArmingStatus.su ./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.cyclo ./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.d ./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.o ./Core/dsdlc_generated/test/test_uavcan.navigation.GlobalNavigationSolution.su ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.AccessCommandShell_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.d ./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.o ./Core/dsdlc_generated/test/test_uavcan.protocol.CANIfaceStats.su ./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.d ./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.o ./Core/dsdlc_generated/test/test_uavcan.protocol.DataTypeKind.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetDataTypeInfo_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetNodeInfo_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.GetTransportStats_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.d ./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.o
	-$(RM) ./Core/dsdlc_generated/test/test_uavcan.protocol.GlobalTimeSync.su ./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.d ./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.o ./Core/dsdlc_generated/test/test_uavcan.protocol.HardwareVersion.su ./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.d ./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.o ./Core/dsdlc_generated/test/test_uavcan.protocol.NodeStatus.su ./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.d ./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.o ./Core/dsdlc_generated/test/test_uavcan.protocol.Panic.su ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.RestartNode_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.d ./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.o ./Core/dsdlc_generated/test/test_uavcan.protocol.SoftwareVersion.su ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.d ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.o ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.KeyValue.su ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.d ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.o ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogLevel.su ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.d ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.o ./Core/dsdlc_generated/test/test_uavcan.protocol.debug.LogMessage.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.Allocation.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.AppendEntries_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Discovery.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.Entry.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.dynamic_node_id.server.RequestVote_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Begin_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.d ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.o ./Core/dsdlc_generated/test/test_uavcan.protocol.enumeration.Indication.su
	-$(RM) ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.BeginFirmwareUpdate_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Delete_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.EntryType.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Error.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetDirectoryEntryInfo_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.GetInfo_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Path.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Read_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.file.Write_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Empty.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.ExecuteOpcode_response.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_request.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.GetSet_response.su
	-$(RM) ./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.NumericValue.su ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.cyclo ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.d ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.o ./Core/dsdlc_generated/test/test_uavcan.protocol.param.Value.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.Broadcast.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_request.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.Call_response.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.Protocol.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.SerialConfig.su ./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.cyclo ./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.d ./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.o ./Core/dsdlc_generated/test/test_uavcan.tunnel.Targetted.su

.PHONY: clean-Core-2f-dsdlc_generated-2f-test

